fix: issue212
sbtinstruments/asyncio-mqtt pull request #216
Opened 2023-05-16 07:16 UTC by vvanglro

This PR fixes #212 .
If `_disconnected` is found to be completed after connecting, it is not correct, so we need to reset it. 
If `_connected` is found to be not completed after disconnecting, then we need to complete and reset it.

2023-05-18 07:52 UTC, frederikaalund commented
Thanks for opening this PR. 👍 Let me have a look. :)

I assume the overall purpose is to make `asyncio_mqtt.Client` [*reusable*](https://docs.python.org/3/library/contextlib.html#reusable-context-managers). I quote the linked docs to save you a click:

> Distinct from both single use and reentrant context managers are “reusable” context managers (or, to be completely explicit, “reusable, but not reentrant” context managers, since reentrant context managers are also reusable). These context managers support being used multiple times, but will fail (or otherwise not work correctly) if the specific context manager instance has already been used in a containing with statement.

**That's the purpose of this PR, right? Let me know if I'm wrong.**

If I'm right, then this PR also relates to #48. I'll provide more feedback after we settle on the intend of this PR.

I hope that makes sense. :)

2023-05-18 08:05 UTC, vvanglro commented
Yes, after adding the judgment, it will become a reusable context. I read #48, and I don’t know much about the publish and QOS in the question. What I can only confirm is that this PR will make aiomqtt a reusable of the context.

2023-05-18 08:19 UTC, vvanglro commented
To be honest, I don't really like to use context in projects, such as the example used in fastapi in your documentation.
I prefer this: (Of course this is just my personal preference😅)
```py
client = aiomqtt.Client("test.mosquitto.org")

@contextlib.asynccontextmanager
async def lifespan(app):
    await clinet.connect()
    yield
    await client.disconnect()
```
I found that you mentioned paho.client.reconnect in #48. 
It would be great if we could integrate this method. See this method literally means reconnect. My good wish is that we can use this method to do More things, such as when the connection is disconnected when calling methods such as subscribing and getting messages, then we will automatically try to reconnect for the user, and the number of reconnections is configurable.
This can be very useful in long-running projects, such as web projects.

2023-05-18 08:41 UTC, frederikaalund commented
> Yes, after adding the judgment, it will become a reusable context. I read https://github.com/sbtinstruments/asyncio-mqtt/issues/48, and I don’t know much about the publish and QOS in the question. What I can only confirm is that this PR will make aiomqtt a reusable of the context.

Great, because that's what we need to test for then! :) What I need from you to merge this PR:
 * Add tests that verify that `asyncio_mqtt.Client` is now reusable (but not reentrant!). Things to consider for the tests:
   * What happens if task A reuses the client while task B listens for messages? Will task B get an exception? Will task B get stuck?
   * What happens if we try to reenter the client? Does it raise an exception? Does it deadlock? Does it work?
   * In general, it's good to both tests for what is supposed to *work* and what is definitely supposed to *not work* (e.g., do we raise proper exceptions that the user can understand?).
 * Change/add to the docs that you can now reuse the client. People will like this feature. 👍

The test part is the most important. I can do the docs if you don't feel like it. :)

---

On the topic of "automatic reconnect": Yes! That would be great to have. It is also quite difficult to get right. 😅 See #6 and #26 for some of the subtleties.
This PR (#216) is the first step towards "automatic reconnect". 👍 We can build the latter on top of the former.

2023-05-18 10:13 UTC, vvanglro commented
OK, I'll do it.

2023-05-19 06:51 UTC, vvanglro commented
This PR changed 5 points:

1. reusable and non reentrant context.
2. Extract the disconnect method.
3. Change message queue to class attribute.
4. Add test case.
5. update ruff version.

2023-05-19 10:51 UTC, frederikaalund requested changes
Looks great and thanks for the detailed tests! 👍 :) The more coverage we get on that front the better.

Have a look at the comments in the review. Let me know if anything is unclear.

### Side note for future reference (not directly relevant to this PR)

Looking through the internals like this again makes me wish that I never exposed `connect` and `disconnect` as part of the public interface. 😅 It's quite the maintenance burden!

Also, now we have this mess of internal state (I'm the cause of that myself):

 * `self._connected: asyncio.Future`
 * `self._disconnected: asyncio.Future`
 * `self._lock: asyncio.Lock`

All three variables have semantic overlap! Really, we should just have the single `_lock` (where "lock acquired" means "client connecting/connected"). Extending on that: Have all internal state inside a tagged union (sum type) in rust-style, concurrency-safe semantics.

In any case, all of that is just food for thought for, e.g., an anyio-based rewrite. :)

2023-05-19 10:51 UTC, frederikaalund commented on asyncio_mqtt/client.py
> +        self._lock: asyncio.Lock = asyncio.Lock()
Good idea to use a `Lock`. 👍 It's a great use case for it.

2023-05-19 10:51 UTC, frederikaalund commented on asyncio_mqtt/client.py
> +            self._disconnected: asyncio.Future[int | mqtt.ReasonCodes | None] = asyncio.Future()  # type: ignore[no-redef]
Skip the type annotation here. We only need it in `__init__` during the member variable declaration. 👍

2023-05-19 10:51 UTC, frederikaalund commented on asyncio_mqtt/client.py
> +            self._connected: asyncio.Future[int | mqtt.ReasonCodes | None] = asyncio.Future()  # type: ignore[no-redef]
Again, skip the type annotation here. :)

2023-05-19 10:51 UTC, frederikaalund commented on asyncio_mqtt/client.py
> +        self, topic_filter: str
Again, unrelated to this PR. Move into a separate PR. Also, that is a breaking change!

2023-05-19 10:51 UTC, frederikaalund commented on asyncio_mqtt/client.py
> +            self._lock.release()
Good use of `finally` 👍

2023-05-19 10:51 UTC, frederikaalund commented on asyncio_mqtt/client.py
> -        """Disconnect from the broker."""
Good idea to move this logic into `disconnect`. 👍

2023-05-19 10:51 UTC, frederikaalund commented on asyncio_mqtt/client.py
> +            self._lock.release()
Hmm, there are some subtle race conditions in this __aexit__ method now. E.g., if `disconnect` raises, we never call `force_disconnect`. That is bad!

My suggestion:
 * **Breaking change**: Make `force_disconnect` private (call it `_force_disconnect`).
 * Make `_force_disconnect` sync (there is no reason for it to be async anyhow).
 * Move `_force_disconnect` into the `finally` block (just above the lock release)

That should fix the race conditions. Note that `_force_disconnect`: (1) never raises and (2) is a no-op if already disconnected.

Does it make sense?

2023-05-19 10:51 UTC, frederikaalund commented on asyncio_mqtt/client.py
> +            self._lock.release()
Mention the breaking change in the changelog as well. In fact, make a changelog entry about this new reentrant Client feature! 😄 Our users would want to know about it!

2023-05-19 10:51 UTC, frederikaalund commented on tests/test_client.py
> +    with pytest.raises(MqttReentrantError):  # noqa: PT012
Excellent! Great basic test. 👍

2023-05-19 10:51 UTC, frederikaalund commented on tests/test_client.py
> +async def test_client_reusable() -> None:
Great. 👍

2023-05-19 10:51 UTC, frederikaalund commented on tests/test_client.py
> +        await anyio.sleep(1)
It's an anti-pattern to `sleep` like that to ensure that `task_a_customer` actually started before we proceed. :)

Instead, use `tg.start`. See this great example from the anyio docs: https://anyio.readthedocs.io/en/3.x/tasks.html#starting-and-initializing-tasks

Let me know if you need help with it. 👍

2023-05-19 10:51 UTC, frederikaalund commented on tests/test_client.py
> +async def test_client_reusable_message() -> None:
Excellent test! Good scenarios. 👍

2023-05-19 14:07 UTC, empicano commented
Hi vvanglro, this is a very cool addition, thank you! 🎉 

> [...] makes me wish that I never exposed connect and disconnect as part of the public interface. 😅 It's quite the maintenance burden!

Our documentation didn't document `connect` and `disconnect` for a long time, in fact, it states: "asyncio-mqtt doesn’t support manual calls to `connect` and `disconnect`."

It'd be a breaking change nonetheless, but I think it's valid to remove it as well. I'm always for simplifying things 😄

2023-05-24 05:35 UTC, frederikaalund commented
Thank you again for your great work on this PR, @vvanglro. :+1: I plan to do the code review this weekend. I'm really tied up until then. :)

2023-05-24 07:36 UTC, vvanglro commented
I'm thinking about some problems,🤯 if we remove connect/disconnect, based main code and the current PR, there will be the following three situations.



The first situation(Base main code, This will establish 10 connections simultaneously):
```py
from asyncio_mqtt import Client


async def run1(message):
    async with Client("192.168.5.24", username="admin", password="123456") as client:
        await client.publish("humidity/outside", payload=message)
        # Maybe it can only be concurrently in context.
        # tasks = [asyncio.create_task(client.publish("humidity/outside", payload=i)) for i in range(10)]
        # await asyncio.gather(*tasks)


async def gather_task1():
    tasks = [asyncio.create_task(run1(i)) for i in range(10)]
    await asyncio.gather(*tasks)
    
    
if __name__ == '__main__':
    import asyncio
    asyncio.get_event_loop().run_until_complete(gather_task1())
```


The two situation(Base current PR, Not reentrant will result in an error):
```py
from asyncio_mqtt import Client


client = Client("192.168.5.24", username="admin", password="123456")


async def run2(message):
    async with client:
        await client.publish("humidity/outside", payload=message)
        # Maybe it can only be concurrently in context.
        # tasks = [asyncio.create_task(client.publish("humidity/outside", payload=i)) for i in range(10)]
        # await asyncio.gather(*tasks)


async def gather_task2():
    tasks = [asyncio.create_task(run2(i)) for i in range(10)]
    await asyncio.gather(*tasks)


if __name__ == '__main__':
    import asyncio
    asyncio.get_event_loop().run_until_complete(gather_task2())
```

The three situation(There is only 1 connection, and no error will be generated):
```py
from asyncio_mqtt import Client


client = Client("192.168.5.24", username="admin", password="123456")

async def run3(message):
    await client.publish("humidity/outside", payload=message)


async def gather_task3():
    await client.connect()
    tasks = [asyncio.create_task(run3(i)) for i in range(10)]
    await asyncio.gather(*tasks)
    await client.disconnect()

if __name__ == '__main__':
    import asyncio
    asyncio.get_event_loop().run_until_complete(gather_task3())
```

So is it possible to consider from other angles and then keep connect/disconnect.
We can not recommend manually calling connect/disconnect unless you understand the logic behind it.

2023-06-08 19:44 UTC, frederikaalund approved these changes

2023-06-08 19:48 UTC, frederikaalund commented
First of all, I apologize about the long delay.

In any case, this PR now looks good to me. 👍 Though I can't merge it in because GitHub says "This branch cannot be rebased due to conflicts". I guess that the main branch updated (probably a bot-based commit) in the meantime.

@vvanglro Can I get you to rebase this PR on top of the master branch? Thanks! Then I'll merge it in right away. :)

2023-06-09 02:46 UTC, vvanglro commented
I can't reproduce the error in CI locally. This seems to be a problem with mypy?

I use python3.8 locally, and python3.10 in CI throws an error.

![image](https://github.com/sbtinstruments/asyncio-mqtt/assets/43594924/5ecfd477-4165-4c8b-847a-3c9e8dc44358)

2023-06-09 16:44 UTC, empicano commented
The CI tests also fail for `3.8`, see https://github.com/sbtinstruments/asyncio-mqtt/actions/runs/5217505877/jobs/9431899291?pr=216; pre-commit doesn't run the unit tests, you can run the tests by running `pytest` 🙂

2023-06-11 08:20 UTC, merged

2023-06-11 08:22 UTC, frederikaalund commented
It was just a simple merge conflict. I added a merge commit on it to fix it. :)

Thank you for a great contribution to asyncio-mqtt. 👍

2023-06-15 19:22 UTC, thalesmaoa commented
This is on the main branch now? Do I still need to call disconnect?

2023-06-17 07:23 UTC, frederikaalund commented
> This is on the main branch now?

Yes, and part of the v1.0.0 release. :)

>Do I still need to call disconnect?

We did not remove `disconnect` (too big of a change). You may still call `connect/disconnect` instead of using the context manager approach.